spring:
  data:
    mongo:
      host: localhost
      port: 27017
      db: foodiebook
---
spring:
  profiles: cloud
  data:
      mongo:
        host: foodie-mongo
        port: 27017
        db: foodiebook
---

---
spring:
  profiles: docker
  data:
      mongo:
        host: foodie-mongo
        port: 27017
        db: foodiebook
---